% returns a cell with all appliance names
function [cellWithAllApplianceNames] = getCellWithAllApplianceNames()

    cellWithAllApplianceNames = { ...
            'Fridge', ...
            'Freezer', ...
            'Microwave', ...
            'Dishwasher', ...
            'Entertainment',...
            'Water kettle', ...
            'Stove', ...     
            'Coffee machine', ...  
            'Washing machine', ...   
            'Dryer', ...         
            'Lamp', ...        
            'PC', ...        
            'Laptop', ...       
            'TV', ...       
            'Stereo', ... 
            'Tablet', ... 
            'Router', ...   
            'Fountain', ...
    };
    
end

